'use strict';
let csrf='',previewId=null,bundle=null,extensionGeneration=null,recoveryBundle=null;
const $=id=>document.getElementById(id);
function message(text){$('message').textContent=text;}
async function api(path,value){
 const response=await fetch('/api/'+path,{method:value===undefined?'GET':'POST',credentials:'same-origin',headers:value===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:value===undefined?undefined:JSON.stringify(value)});
 const result=await response.json();if(result.csrf)csrf=result.csrf;
 if(!response.ok){if(response.status===401&&result.error!=='CSRF_REJECTED'){$('management').hidden=true;$('login').hidden=false;}throw Error(result.error||'REQUEST_FAILED');}
 return result.data===undefined?result:result.data;
}
async function run(fn){try{await fn();}catch(e){message(e.message);try{await api('session');}catch(_){} }}
async function refresh(){const state=await api('status');bundle=state.activeBundle;recoveryBundle=state.recoveryBundle||null;$('status').replaceChildren();for(const [key,title] of Object.entries({state:'真实状态',result:'控制结果',error:'错误',activeBundle:'当前 bundle',MainPID:'PID',InvocationID:'InvocationID',executableSha256:'DAE 二进制 SHA-256',configSha256:'实际配置 SHA-256'})){let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=title;dd.textContent=state[key]??'—';$('status').append(dt,dd);}if(state.state==='rollback-needed'||state.result==='MANUAL_INTERVENTION_REQUIRED')message('需要恢复或人工介入：'+(state.result||state.error||state.state));}
async function extensions(){let result=await api('extensions');if(result.setupRequired)message('请先完成官方 2023 页面设置，再运行 install.sh --connect-daed 授权配置采集。');else{await api('bind-extensions',{});result=await api('extensions');}extensionGeneration=result.generation;$('extensions').replaceChildren();for(const [section,profiles] of Object.entries(result.records))for(const [profile,fields] of Object.entries(profiles))for(const [field,state] of Object.entries(fields)){const row=document.createElement('div');row.className='extension';const label=document.createElement('label');label.textContent=section+' / '+profile+' / '+field;const presence=document.createElement('select');for(const [value,text] of [['absent','未设置'],['present','明确设置']]){let option=document.createElement('option');option.value=value;option.textContent=text;presence.append(option);}presence.value=state.present?'present':'absent';const input=document.createElement('input');input.value=state.present?JSON.stringify(state.value):'';input.placeholder='JSON 值，例如 false、true、0';const save=document.createElement('button');save.textContent='保存';save.onclick=()=>run(async()=>{let value=presence.value==='absent'?{present:false}:{present:true,value:JSON.parse(input.value)};await api('extensions',{expected:extensionGeneration,section,profile,field,state:value});previewId=null;$('apply').disabled=true;$('validate').disabled=true;await extensions();message('扩展已保存；请重新预览。');});label.append(presence,input);row.append(label,save);$('extensions').append(row);}}
$('login').onsubmit=event=>{event.preventDefault();run(async()=>{const c=await api('challenge');csrf=c.csrf;const form=new FormData($('login'));await api('login',{token:form.get('token')});$('login').reset();$('login').hidden=true;$('management').hidden=false;message('已登录');await refresh();await extensions();});};
$('refresh').onclick=()=>run(refresh);
$('logout').onclick=()=>run(async()=>{await api('logout',{});csrf='';previewId=null;bundle=null;$('status').replaceChildren();$('extensions').replaceChildren();$('preview-result').textContent='';$('management').hidden=true;$('login').hidden=false;message('已退出');});
$('preview').onclick=()=>run(async()=>{const p=await api('preview',{});previewId=p.previewId;$('preview-result').textContent=JSON.stringify(p,null,2);$('validate').disabled=false;$('apply').disabled=true;message('预览已生成，尚未应用。');});
$('validate').onclick=()=>run(async()=>{await api('validate',{previewId});$('apply').disabled=false;message('官方静态校验通过；不代表数据面验收通过。');});
$('apply').onclick=()=>run(async()=>{const outcome=await api('apply',{previewId});await refresh();if(outcome.result.error)throw Error(outcome.result.error);if(!['APPLIED','ALREADY_APPLIED'].includes(outcome.result.result))throw Error(outcome.result.result||'APPLY_NOT_CONFIRMED');message('应用请求已完成，请核对真实状态。');});
for(const button of $('actions').querySelectorAll('button'))button.onclick=()=>run(async()=>{const target=button.dataset.action==='recover'?recoveryBundle:bundle;if(!target)throw Error('没有可执行此动作的 bundle');const result=await api(button.dataset.action,{bundleId:target});await refresh();if(result.error)throw Error(result.error);message(result.result||result.state||'请求完成');});
run(async()=>{try{await api('session');}catch(_){return;}$('login').hidden=true;$('management').hidden=false;await refresh();await extensions();});
